[package]
name = "img2piet"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
anyhow = "1.0.55"
cached = "0.31.0"
clap = { version = "3.1.2", features = ["derive"] }
image = "0.24.1"
rayon = "1.5.1"
